# This workflow updates the open PRs in
# _config.yml each time a pull request is made
# or there is a push to main.  It does not handle
# the rebuild of the storybook or javadoc; that's handled
# separately based on which files were modified.

name: "01-gh-pages-pr-table: Rebuild table of PRs"
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
          

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: read

jobs: 
  build-basic-site:
    name: Build Basic Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Append name of site and prs to _config.yml
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: | 
          echo "Running workflow from https://github.com/ucsb-cs156/workflows/01-gh-pages-pr-table.yml"
          echo "Running in repo: ${{github.repository}}"
          CONFIG_YML=frontend/docs-index/_config.yml
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          echo "repo: ${OWNER_PLUS_REPOSITORY}" >> ${CONFIG_YML}
          echo "owner: ${OWNER}" >> ${CONFIG_YML}
          echo "repo_name: ${REPOSITORY}" >> ${CONFIG_YML}    
          echo "pull_requests: $(gh pr list -s open --json url,author,number,title,headRefName)" >> ${CONFIG_YML}
    - name: Compose web site
      run: |
        mkdir -p site
        cp -r frontend/docs-index/* site
  
    - name: Deploy ðŸš€    
      if: always() # always upload artifacts, even if tests fail
      uses: Wandalen/wretry.action@master
      with:
        action: JamesIves/github-pages-deploy-action@v4
        attempt_limit: 3
        attempt_delay: 5000
        with: |
          folder: site # The folder the action should deploy.
          branch: gh-pages
          clean: false # Automatically remove deleted files from the deploy branch